CREATE DATABASE fotr_db;
CREATE USER fotr_dev@locahost IDENTIFIED BY 'Password';

GRANT ALL PRIVILEGES  ON `fotr\_db`.* TO 'fotr_dev'@'locahost';
FLUSH PRIVILEGES;


CREATE TABLE IF NOT EXISTS fotr_db.`station_images` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`station` varchar(64) NOT NULL DEFAULT "**ERROR: MISSING MONITORING STATION**",
	`location` varchar(64) NOT NULL DEFAULT "**ERROR: MISSING STATION LOCATION**",
	`photo` varchar(255) NOT NULL DEFAULT "**ERROR: MISSING PHOTO**",
	PRIMARY KEY(`id`)
);